# Generated by Django 5.2.4 on 2026-05-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcallsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создана'),
        ),
    ]
