# Generated by Django 5.2.4 on 2026-05-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='day_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено дневное напоминание'),
        ),
        migrations.AddField(
            model_name='product',
            name='reminder_2h_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено напоминание за 2 часа'),
        ),
    ]
