# Generated by Django 5.2.4 on 2026-05-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_day_reminder_sent_product_reminder_2h_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='day_reminder_sent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reminder_2h_sent',
        ),
    ]
