# Generated by Django 5.2.4 on 2026-05-09 08:05

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_day_reminder_sent_and_more'),
        ('orders', '0004_appointment_day_reminder_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='availabledate',
            options={'ordering': ['date'], 'verbose_name': 'Дата', 'verbose_name_plural': 'Даты'},
        ),
        migrations.AlterModelOptions(
            name='availabletime',
            options={'ordering': ['time'], 'verbose_name': 'Время', 'verbose_name_plural': 'Время'},
        ),
        migrations.AddField(
            model_name='availabledate',
            name='exclude_products',
            field=models.ManyToManyField(blank=True, help_text='Эти услуги НЕ будут видеть эту дату', related_name='excluded_dates', to='main.product', verbose_name='Исключить для этих услуг'),
        ),
        migrations.AddField(
            model_name='availabledate',
            name='specific_products',
            field=models.ManyToManyField(blank=True, help_text='Если не выбрано - дата доступна для всех услуг', to='main.product', verbose_name='Только для этих услуг'),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='available_for_products',
            field=models.ManyToManyField(blank=True, help_text='Если не выбрано - время доступно для всех услуг', to='main.product', verbose_name='Доступно для услуг'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availabledate',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['product', 'date'], name='orders_appo_product_5183be_idx'),
        ),
    ]
