# Generated by Django 5.2.4 on 2026-05-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_day_reminder_sent_and_more'),
        ('orders', '0005_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time', 'product')},
        ),
    ]
