# Generated by Django 5.2.4 on 2026-05-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_day_reminder_sent_and_more'),
        ('orders', '0006_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletime',
            name='available_for_products',
        ),
        migrations.AddField(
            model_name='availabletime',
            name='allow_other_services',
            field=models.BooleanField(default=False, verbose_name='Разрешить другие услуги в это время'),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='booked_for_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product', verbose_name='Забронировано для услуги'),
        ),
    ]
