# Generated by Django 5.2.4 on 2026-05-09 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_day_reminder_sent_and_more'),
        ('orders', '0007_remove_availabletime_available_for_products_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='orders_appo_date_id_88ce03_idx',
        ),
        migrations.RemoveIndex(
            model_name='availabletime',
            name='orders_avai_date_id_706566_idx',
        ),
        migrations.RemoveIndex(
            model_name='availabletime',
            name='orders_avai_time_0c36b3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='availabletime',
            name='allow_other_services',
        ),
        migrations.RemoveField(
            model_name='availabletime',
            name='booked_for_product',
        ),
        migrations.RemoveField(
            model_name='availabletime',
            name='freely',
        ),
        migrations.AddField(
            model_name='availabletime',
            name='available_for_products',
            field=models.ManyToManyField(blank=True, help_text='Если не выбрано - время доступно для всех услуг', to='main.product', verbose_name='Доступно для услуг'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Дневное напоминание'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reminder_2h_sent',
            field=models.BooleanField(default=False, verbose_name='Напоминание за 2 часа'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='orders.availabletime', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'time', 'product'], name='orders_appo_date_id_c8a38b_idx'),
        ),
        migrations.AddIndex(
            model_name='availabletime',
            index=models.Index(fields=['date', 'time'], name='orders_avai_date_id_6b3246_idx'),
        ),
    ]
